# This is a config for E2B sandbox template.
# You can use template ID (0xtggp9k16lx53bp82aa) or template name (buildbuddy-nextjs-test-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("buildbuddy-nextjs-test-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("buildbuddy-nextjs-test-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('buildbuddy-nextjs-test-1')

team_id = "a156f7c8-7a9c-4e8a-b564-a90d548a02a2"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "buildbuddy-nextjs-test-1"
template_id = "0xtggp9k16lx53bp82aa"
